# fly.toml app configuration file generated for backend-oltech on 2024-06-20T12:43:21-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-oltech'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
